### PR TITLE
Update Elkanoto to match current sklearn behavior

### PR DESCRIPTION
**Pull request by mepland**
Match current sklearn behavior:
- Save `classes_`
- Return `0` instead of `-1` in `predict()`
- Match returned array dimensions for `predict_proba()` and `predict()`

### CODE REVIEW

**Comment by mepland** [comment]
Should address https://github.com/pulearn/pulearn/issues/20

**Comment by mepland** [comment]
Addresses [this comment](https://github.com/pulearn/pulearn/issues/15#issuecomment-856541137) indirectly, as Elkanoto's `predict_proba` should now also return a 2d array:

> weighted can also give this, but seems to do so less often. bagging seems fine in this respect, but it's predict_proba gives 2d arrays when the same thing gives 1d arrays on the other classifiers

**Comment by shaypal5** [comment]
Approving the run of builds / tests!
Let's see how it goes!

**Comment by mepland** [comment]
@shaypal5 looks like the non-3.7 tests failed, but they are also failing for [master](https://github.com/pulearn/pulearn/actions/runs/3869705202)?

**Comment by mepland** [comment]
@shaypal5 @kernc @kjappelbaum what is the status of the 3.8+ tests? Can we still merge this PR if the failing tests are due to other parts of the package?

**Comment by shaypal5** [comment]
Yeah, go ahead.

I'll open an issue on fixing 3.8+ related issues (actually stems from relying on old numpy and sklearn versions).

**Pull request merged**
